# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaVLhbsXLP7Calu2Q1orqVIPQuHS2LKT

# Building a Basic Neural Network using only Numpy to predict values of the MNIST Dataset
"""

import numpy as np

"""# Core Components of a Deep Neural Network
A basic neural network requires the following components to function:

1. Data Representation (Tensors): Multi-dimensional arrays that hold the input features (e.g., pixels) and target labels.

2. Architecture (Layers & Neurons): The structural design of the network, defining the depth (number of layers) and width (neurons per layer) of the model.

3. Model Parameters (Weights & Biases): The learnable variables that are adjusted during training to capture patterns in the data.

4. Activation Functions: Non-linear mathematical functions (like ReLU or Softmax) that allow the network to learn complex, non-linear relationships.

5. Forward Pass: The process of passing input data through the network layers to generate a prediction.

6. Loss Function: A method to quantify the "error" by measuring the difference between the model's prediction and the actual ground truth.

7. Backpropagation: The application of the Chain Rule to calculate the gradient (slope) of the loss with respect to every weight and bias in the model.

8. Optimization (Gradient Descent): The strategy used to update the model parameters in the opposite direction of the gradient to minimize the loss
"""

# Activation Functions

# 1. ReLU Function:
class ReLU:
  """
  In the forward pass it is a simple filter:
  - if number is positive, pass the number through unchanged
  - if number is negative, it converts the number to 0

  In the backward pass, we are carrying a Gradient (in short is a signal that says 'the error was this big, please change weights')
  The job of the backward pass is to decide how much of that signal to pass back to the previous layers
  Mathematically, the slope of ReLU is:
  - 1 for all positive numbers
  - 0 for all negative numbers
  """

  def forward(self, x):
    self.input = x
    return np.maximum(0, x)

  def backward(self, grad_output):
    grad_input = grad_output.copy()
    grad_input[self.input<=0] = 0
    return grad_input

# 2. Softmax Function:
class Softmax:
  """
  In the forward pass we convert the scores into Probabilities
  When the model finishes the math, the last layer outputs raw scores called logits.
  We want these be in the format of Probabilities.

  In the forward pass we calculate the exponential of every number, to ensure it is positive, and it also amplifies the answer.
  We subtract '-np.max(x)' purely to ease computational load, the ratios stay the exact same, while the numbers stay small and stable.
  We then normalize the outputs, so that they equal exactly 1.0

  In the backward pass:
  - We take a shortcut, the derivative of Softmax alone, would involve Jacobian Matrix
    However, if we pair Softmax with Cross-Entropy Loss, their combined calculus cancels most of it out
    which leaves the formula to be: output (model predicted val) - target (actual truth)
  """
  def forward(self, x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    self.output = exp_x / np.sum(exp_x, axis=1, keepdims=True)
    return self.output

  def backward(self, target):
    return self.output - target

# Now we need to create the Layers (equivalent of nn.Linear)

class DenseLayer:
  """
  Creating the parameters:
  - weight: strength of connection between neurons
  - bias: offset of the neurons, to give the model more flexibility

  Initialization of the weights:
  -  If you initialize weights to zero, the model won't learn (symmetry breaking).
     If you make them too big, the math explodes.
     Multiplying 'sqrt{2 / n}' keeps the variance of the outputs consistent across layers—essential for deep networks.

  The forward pass:
  - We save self.input as it is needed later in the backward pass to know which inputs were responsible for the error.
  - Every input is multiplied by a weight, summed up and then a bias is added.
  - Formula: Y = X . W + b

  The backward pass:
  This is the key part of this network, it does 3 things simultaneously using chain rule.
  - Distributes Blame (gradients):
      1. weight gradient: how much did the weights cause the error
      2. bias gradient: how much did the bias cause the error
  - Passing the signal back (grad_input):
      - The current layer needs to tell the layer before it, 'here is your share of the error'.
  - The Learning step (Optimizer):
      - Update the parameters (weights and bias) by taking a small step (learning rate (lr)) in the opposite direction of the gradient to reduce error
  """
  def __init__(self, n_inputs, n_neurons):
    self.weight = np.random.randn(n_inputs, n_neurons) * np.sqrt(2./n_inputs)
    self.bias = np.zeros((1, n_neurons))

  def forward(self, x):
    self.input = x
    return np.dot(x, self.weight) + self.bias

  def backward(self, grad_output, lr):
    m = self.input.shape[0]
    self.grad_weight = np.dot(self.input.T, grad_output) / m
    self.grad_bias = np.sum(grad_output, axis=0, keepdims=True) / m

    # Calculating gradient for next layer (moving backwards)
    grad_input = np.dot(grad_output, self.weight.T)

    # Update the parameters
    self.weight -= lr * self.grad_weight
    self.bias -= lr * self.grad_bias

    return grad_input

class NeuralNetwork:
  def __init__(self, layers):
    self.layers = layers

  def forward(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    return x

  def backward(self, grad, lr):
    for layer in reversed(self.layers):
      if isinstance(layer, DenseLayer):
        grad = layer.backward(grad, lr)
      else:
        grad = layer.backward(grad)
    return grad

import numpy as np

def prepare_mnist():
    """
    Downloads the MNIST dataset, normalizes pixel values,
    and converts integer labels into one-hot encoded vectors.

    Returns:
        X: A NumPy array of shape (60000, 784) containing flattened, scaled images.
        y: A NumPy array of shape (60000, 10) containing one-hot encoded labels.
    """
    from sklearn.datasets import fetch_openml

    # 1. Fetch the raw data from OpenML (70,000 images total)
    print("Fetching MNIST... might take a minute...")
    mnist = fetch_openml('mnist_784', version=1, as_frame=False)

    # 2. Extract images and scale them
    # Dividing by 255.0 converts integer [0, 255] to float [0.0, 1.0]
    # This ensures gradients remain stable during backpropagation.
    X = mnist.data.astype('float32') / 255.0

    # 3. One-Hot Encode the labels
    # np.eye(10) creates an identity matrix.
    # Indexing it with the label (e.g., [3]) picks the row where the 3rd index is 1.
    y = np.eye(10)[mnist.target.astype('int')]

    # 4. Slice the data
    # We take the first 60,000 for training, leaving 10,000 for testing.
    return X[:60000], y[:60000]

X, y = prepare_mnist()

# Build architecture
model = NeuralNetwork([
    DenseLayer(784, 128),
    ReLU(),
    DenseLayer(128, 10),
    Softmax()
])

lr = 0.1  # Now that gradients are averaged, we can use a higher LR
epochs = 100

for epoch in range(epochs):
    # Forward Pass
    probs = model.forward(X)

    # Calculate Metrics
    loss = -np.mean(np.sum(y * np.log(probs + 1e-8), axis=1))
    predictions = np.argmax(probs, axis=1)
    true_labels = np.argmax(y, axis=1)
    accuracy = np.mean(predictions == true_labels)

    # Backward Pass
    model.backward(y, lr)

    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.4f} | Accuracy: {accuracy*100:.2f}%")

print(f"\nFinal Training Accuracy: {accuracy*100:.2f}%")